// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEQy1WXmKDphBpLVF76vMOXIVA32WRkoY',
    appId: '1:209993652402:web:6e008ae344fd73b39651ab',
    messagingSenderId: '209993652402',
    projectId: 'voting-app-3b3be',
    authDomain: 'voting-app-3b3be.firebaseapp.com',
    databaseURL: 'https://voting-app-3b3be-default-rtdb.firebaseio.com',
    storageBucket: 'voting-app-3b3be.appspot.com',
    measurementId: 'G-Q5BS48S64M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqLzrYrvmjy-2UzA5qXwjH2qDypJo7iGE',
    appId: '1:209993652402:android:183a58802013588e9651ab',
    messagingSenderId: '209993652402',
    projectId: 'voting-app-3b3be',
    databaseURL: 'https://voting-app-3b3be-default-rtdb.firebaseio.com',
    storageBucket: 'voting-app-3b3be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1g0xNOo1kDeG8LQbFA_CIxWqiC5MzJtU',
    appId: '1:209993652402:ios:902fb8a31d21491d9651ab',
    messagingSenderId: '209993652402',
    projectId: 'voting-app-3b3be',
    databaseURL: 'https://voting-app-3b3be-default-rtdb.firebaseio.com',
    storageBucket: 'voting-app-3b3be.appspot.com',
    iosClientId: '209993652402-051m9et5q46ptgs7fi5kkn8ifgt0f4hg.apps.googleusercontent.com',
    iosBundleId: 'com.voice.voting',
  );
}
